#!/usr/bin/env bash
set -euo pipefail

# ensure addons dir is present
mkdir addons || true

# setup hook for .zshrc
if grep 'DOTFILES_DIR' &>/dev/null <~/.zshrc; then
  echo "dotfile already setup in ~/.zshrc"
  exit 0
fi
declare here
here="$( cd "$( dirname "$0" )" && pwd )"
cat <<EOF >> ~/.zshrc
export DOTFILES_DIR="${here:?}"
source "\${DOTFILES_DIR:?}/.zshrc"
EOF
